/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_rtmpvideo_RtmpH264 */

#ifndef _Included_com_android_rtmpvideo_RtmpH264
#define _Included_com_android_rtmpvideo_RtmpH264
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_rtmpvideo_RtmpH264
 * Method:    initRtmp
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_android_rtmpvideo_RtmpH264_initRtmp
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_android_rtmpvideo_RtmpH264
 * Method:    sendSpsAndPps
 * Signature: ([BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_android_rtmpvideo_RtmpH264_sendSpsAndPps
  (JNIEnv *, jclass, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_android_rtmpvideo_RtmpH264
 * Method:    sendVideoFrame
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_android_rtmpvideo_RtmpH264_sendVideoFrame
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     com_android_rtmpvideo_RtmpH264
 * Method:    stopRtmp
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_android_rtmpvideo_RtmpH264_stopRtmp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
